### ISSUE TITLE
sin Composer?

### ISSUE THREAD

**Issue by mayeco** [autentifactor/php_sdk#1]
Agregar composer.json

**Comment by molekilla** [comment]
hola @mayeco , lo estaremos revisando, gracias ! 

CC @rbonillajr

**Comment by molekilla** [comment]
seria usar esta lib

https://packagist.org/packages/curl/curl

para tener Composer support

**Comment by mayeco** [comment]
@molekilla es para hacer que la libreria pueda instalarse con composer

https://getcomposer.org/doc/02-libraries.md

**Comment by molekilla** [comment]
done
