### ISSUE TITLE
Usar una Guzzle como cliente

### ISSUE THREAD

**Issue by mayeco** [autentifactor/php_sdk#2]
Para peticiones API es preferible usar Guzzle es muy estable.

http://guzzle.readthedocs.org/en/latest/

https://github.com/guzzle/guzzle

**Comment by molekilla** [comment]
muchas gracias!

**Comment by molekilla** [comment]
done

https://github.com/autentifactor/php_sdk/blob/master/lib/autentifactor_guzzle.php
